CREATE DATABASE IF NOT EXISTS sock_user;
CREATE DATABASE IF NOT EXISTS sock_catalog;
CREATE DATABASE IF NOT EXISTS sock_cart;
CREATE DATABASE IF NOT EXISTS sock_order;
CREATE DATABASE IF NOT EXISTS sock_payment;
CREATE DATABASE IF NOT EXISTS sock_shipping;