apiVersion: v1
kind: Secret
metadata:
  name: sock-cart-mysql-secret
  namespace: sock-cart
stringData:
  hostname: sock-cart-mysql.sock-cart.svc.cluster.local
  port: "3306"
  username: sockshop
  password: sockshop
  database: sock_cart