apiVersion: v1
kind: Secret
metadata:
  name: sock-user-mysql-secret
  namespace: sock-user
stringData:
  hostname: sock-user-mysql.sock-user.svc.cluster.local
  port: "3306"
  username: sockshop
  password: sockshop
  database: sock_user