apiVersion: v1
kind: Secret
metadata:
  name: sock-catalog-mysql-secret
  namespace: sock-catalog
stringData:
  hostname: sock-catalog-mysql.sock-catalog.svc.cluster.local
  port: "3306"
  username: sockshop
  password: sockshop
  database: sock_catalog